options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: maven-cache
      path: /root/.m2

steps:
  # 建構 Docker 映像檔
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Module
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--file'
      - '${_MODULE_NAME}/Dockerfile'
      - '.'

  # Push 到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Image
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:$COMMIT_SHA'

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-to-Cloud-Run
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=191169836402-compute@developer.gserviceaccount.com'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:$COMMIT_SHA'