steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Module
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--file'
      # _MODULE_NAME 是在 cloud build 上自定義的變數，用以指定個別模組的 Dockerfile 路徑
      - '${_MODULE_NAME}/Dockerfile'
      # 指定從根目錄Build，才能抓到 security 共用模組
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

#  避免 if 'build.service_account' is specified, the build must either 錯誤
options:
  logging: CLOUD_LOGGING_ONLY