# gcloud builds submit --config cloudbuild.yaml --substitutions=_SERVICE_NAME=cathay-demo-account,_MODULE_NAME=account .
# gcloud builds submit --config cloudbuild.yaml --substitutions=_SERVICE_NAME=cathay-demo-image,_MODULE_NAME=image .

options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: maven-cache
      path: /root/.m2

steps:
  # 建構 Docker 映像檔
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Image
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:k8s'
      - '--file'
      - '${_MODULE_NAME}/Dockerfile'
      - '.'

  # Push 到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Image
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:k8s'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cathay-demo-image/${_SERVICE_NAME}:k8s'