spring:
  config:
    import: sm@
  cloud:
    gcp:
      project-id: golden-medium-471501-p8
      sql:
        database-name: postgres
        instance-connection-name: golden-medium-471501-p8:asia-east1:cathay-demo
  datasource:
    username: ${sm@cathay-demo-db-username}
    password: ${sm@cathay-demo-db-password}

jwt:
  secret: ${sm@cathay-demo-key}
  expiration: 3600000