spring:
  config:
    import: sm://
  cloud:
    gcp:
      project-id: golden-medium-471501-p8
      sql:
        database-name: postgres
        instance-connection-name: golden-medium-471501-p8:asia-east1:cathay-demo
  datasource:
    username: postgres
    password: 1qaz@WSX

jwt:
  expiration: 3600000