spring:
  config:
    import: sm://
  cloud:
    gcp:
      project-id: golden-medium-471501-p8
  datasource:
    url: jdbc:postgresql://35.201.157.171:5432/postgres
    username: postgres
    password: 1qaz@WSX
    driver-class-name: org.postgresql.Driver
jwt:
  expiration: 3600000